version: '3.3'
services:
  postgres:
    container_name: db
    image: florinutz/postgres-playground
    build: 
      context: build
      args: 
        importUser: flo
        importDb: playground
    ports:
    - "5432:5432"
    volumes:
    - db-data:/var/lib/postgresql/data
    environment: 
      POSTGRES_USER: flo
      POSTGRES_PASSWORD: eenie
      POSTGRES_DB: playground
volumes:
  db-data: